version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: comaday-postgres
    restart: always
    environment:
      POSTGRES_DB: comaday
      POSTGRES_USER: comaday_user
      POSTGRES_PASSWORD: comaday_password
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U comaday_user -d comaday"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
